ims.web/Areas/Admin/Models/StudentsViewModel.cs
using Ims.web.BaseModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Ims.web.Areas.Admin.Models
{
    public class StudentsViewModel : StudentBase
    {
        public string FormNumber { get; set; }
        public DateTime EnrollmentDate { get; set; }

        public int CityID { get; set; }
        [Required]
        [Display(Name = "City")]
        public string CityName { get; set; }

        public int QualificationID { get; set; }

        public int BatchID { get; set; }
        [Required]
        [Display(Name = "Batch")]
        public string BatchName { get; set; }

        public int TrackID { get; set; }
        [Required]
        [Display(Name = "Track")]
        public string TrackName { get; set; }

        [Required]
        [Display(Name = "Joining Date")]
        public DateTime JoiningDate { get; set; }

        public StudentsViewModel()
        {
            
        }
    }
}

ims.web/Areas/Admin/Controllers/StudentsController.cs
using Framework.Data.Infrastructure;
using Framework.Data.Repositories;
using Framework.Entities;
using Ims.web.Areas.Admin.Models;
using Ims.web.Core;
using Ims.web.Extensions;
using Ims.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ims.web.Areas.Admin.Controllers
{
    public class StudentsController : ImsControllerBase
    {
        private readonly IEntityBaseRepository<Students> studentsRepository;
        private readonly IEntityBaseRepository<Enquiry> enquiryRepository;

        public StudentsController(IEntityBaseRepository<Students> studentsrepository,
                IEntityBaseRepository<ErrorLog> errorRepository, IUnitOfWork unitOfWork,
                IEntityBaseRepository<Enquiry>enquiryrepository) 
            :base(errorRepository,unitOfWork)

        {
            this.studentsRepository = studentsrepository;
            this.enquiryRepository = enquiryrepository;

        }

        public ActionResult Index()
        {
            var students = studentsRepository.GetAll()
                .OrderByDescending(o =>o.EnrollmentDate)
                .ToList();
            // Paging logic to be implemented.....

            List<StudentsViewModel> studentVM = new List<StudentsViewModel>();
            students.MapStudentViewModel(studentVM);
            return View(studentVM);
        }

        public ActionResult Enroll()
        { 
            return View();
        }

        [HttpPost]
        public ActionResult Enroll(StudentsViewModel studentVM)
        {
            Students student = new Students();
            student.UpdateEnrollment(studentVM);
            studentsRepository.Add(student);
            unitOfWork.Commit();
            // to do handle exception cases by passing paramter to the following view.
            return RedirectToAction("Message");            
        }

        public ActionResult Enquries(int page = 1, int pageSize = 10, string filter = null)
        {
            int currentPage = page;
            int currentPageSize = pageSize;
            var enquries = enquiryRepository.GetAll()
                        .OrderByDescending(e => e.ID)
                        .Take(currentPageSize).ToList();
            List<EnquiryViewModel> enquriesVM = new List<web.Models.EnquiryViewModel>();
            enquries.MapEnquiryViewModel(enquriesVM);

            return View(enquriesVM);
        }
        public ActionResult Message()
        {
            return View("Confirmation");
        }
    }
}

ims.web/Areas/Admin/Views/Students/Confirmation.cshtml
@{
    ViewBag.Title = "Student Registration Status";
}

<h3>Student Information saved sucessfully. Initiate Course fee payments and student starter kit generation.</h3>
<br/><br /><br /><br /><br /><br /><br /> <!--to be added more info ..-->

ims.web/Areas/Admin/Views/Students/Enquries.cshtml
@model IEnumerable<Ims.web.Models.EnquiryViewModel>
@{
    ViewBag.Title = "Enquries";
}
<br/>
<h4> Recent Enquries</h4>
<hr />
@Html.Partial("_SearchBar")
<table class="table">
    <thead>
        <tr>            
            <th>Student Name</th>            
            <th>Email Address</th>
            <th>Contact Number</th>
            <th>Course Name </th>
            <th>Enquiry Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var st in Model)
        {
            <tr>                
                <td>@st.FirstName &nbsp; @st.LastName</td>
                <td>@st.EmailAddress</td>
                <td>@st.Mobile</td>
                <td>@st.CourseName</td>                                
                <td>@st.EnquiryDate.ToShortDateString()</td>
                <td> 
                    <button type="button"
                            class="btn btn-link"
                            data-toggle="modal"
                            data-target="#follow-up">
                        Follow up
                    </button>

                </td>
            </tr>
        }
    </tbody>
</table>

<div id="follow-up" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Student Name</h4>
            </div>
            <div class="modal-body">
                <p>to be implemented...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

ims.web/Areas/Admin/Views/Students/Enroll.cshtml
@model Ims.web.Areas.Admin.Models.StudentsViewModel

@using (Html.BeginForm("Enroll", "Students", FormMethod.Post, new
{ role = "form", autocomplete = "off" }))

//@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <br/>
    <h4>Entroll Student</h4>
    <hr />
    <div class="form-horizontal">
                
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.GenderID, new SelectList(
                new List<Object>{
                new { value = 0 , text = "Unknown"},
                new { value = 1 , text = "Male" },
                new { value = 2 , text = "Female" }
                    }, "value", "text", 0), new { @class = "form-control" })
            </div>
        </div>

        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" , placeholder = "Select City" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BatchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BatchName, new { htmlAttributes = new { @class = "form-control" , placeholder = "Select Batch" } })
                @Html.ValidationMessageFor(model => model.BatchName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TrackName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrackName, new { htmlAttributes = new { @class = "form-control" , placeholder = "Select Track" } })
                @Html.ValidationMessageFor(model => model.TrackName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="hidden" value="0" name="CourseID" id="CourseID" />
        <input type="hidden" value="0" name="TrackID" id="TrackID" />
        <input type="hidden" value="0" name="BatchID" id="BatchID" />
        <input type="hidden" value="0" name="CityID" id="CityID" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-primary" />
                <input type="Reset" value="Reset" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
          $(document).ready(function () {
              enrollmodule.init();
           });
    </script>
}
 

 

ims.web/Areas/Admin/Views/Students/Index.cshtml
@model IEnumerable<Ims.web.Areas.Admin.Models.StudentsViewModel>
@{
    ViewBag.Title = "Enrolled Students";
}

<br/>
<h4>Recent Enrollments</h4>
<hr/>
@Html.Partial("_SearchBar")
<table class="table">
     
    <thead>
        <tr>
            <th>Student ID</th>
            <th>Student Name</th>
            <th>Contact Number</th>
            <th>Email Address</th>
            <th>Course</th>
            <th>Enrollment Date</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var st in Model)
        {
            <tr>
                <th scope="row">@st.ID</th>
                <td>@st.FirstName &nbsp; @st.LastName</td>
                <td>@st.Mobile</td>
                <td>@st.EmailAddress</td>
                <td>@st.CourseName</td>
                <td>@st.EnrollmentDate.ToShortDateString()</td>
                <td>       
                    <button type="button" 
                            class="btn btn-link"
                            data-toggle="modal" 
                            data-target="#viewdetails">Details</button>
                </td>
            </tr>
        }

    </tbody>
</table>
<div id="viewdetails" class="modal modal-wide fade">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Student Details</h4>
            </div>
            <div class="modal-body">
                <p>to be implemented.....</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                
            </div>
        </div>

    </div>
</div>


 