ims.web/Models/EnquiryViewModel.cs
using Ims.web.BaseModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ims.web.Models
{
    public class EnquiryViewModel : StudentBase
    {
        [Display(Name = "Enquiry Date")]
        public DateTime EnquiryDate { get; set; }
        [Display(Name = "Remarks")]
        public string Remarks { get; set; }
      
    }
}

ims.web/Controllers/EnquiryController.cs
using Framework.Data.Infrastructure;
using Framework.Data.Repositories;
using Framework.Entities;
using Ims.web.Core;
using Ims.web.Extensions;
using Ims.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ims.web.Controllers
{
    public class EnquiryController : ImsControllerBase
    {
        private readonly IEntityBaseRepository<Enquiry> enquiryRepository;
        
        public EnquiryController(IEntityBaseRepository<Enquiry> enquiryrepository,
                IEntityBaseRepository<ErrorLog>errorRepository,IUnitOfWork unitOfWork) 
            :base(errorRepository,unitOfWork)

        {
            this.enquiryRepository = enquiryrepository;
            
        }
            
        [AllowAnonymous]
        public ActionResult AddEnquiry()
        {
           return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult AddEnquiry(EnquiryViewModel enquiryDetails)
        {
            Enquiry enquiry = new Enquiry();
            enquiry.UpdateEnquiry(enquiryDetails);
            enquiryRepository.Add(enquiry);
            unitOfWork.Commit();
            // to do handle exception by passing object to below method.
            return RedirectToAction("Message");
        }
        public ActionResult Message()
        {
            return View("ThankYou");
        }
    }
}

ims.web/Views/Enquiry/AddEnquiry.cshtml
@model Ims.web.Models.EnquiryViewModel
@{
    ViewBag.Title = "Course Enquiry";
}

<h3>@ViewBag.Title.</h3>
<hr />

@using (Html.BeginForm("AddEnquiry", "Enquiry", FormMethod.Post, new
{ @class = "form-horizontal", role = "form" , autocomplete = "off" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(m => m.CourseName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.CourseName, new { @class = "form-control", placeholder = "Select Course" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.DOB, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.DOB, new { @class = "form-control" })
        </div>
    </div>
       
    <div class="form-group">
        @Html.LabelFor(m => m.GenderID, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.GenderID, new SelectList(
            new List<Object>{
            new { value = 0 , text = "Unknown"},
            new { value = 1 , text = "Male" },
            new { value = 2 , text = "Female" }
            },"value","text",0), new { @class = "form-control" })        
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Telephone, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Telephone, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Mobile, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Mobile, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.EmailAddress, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
        </div>
    </div>
 
    <div class="form-group">
        @Html.LabelFor(m => m.Remarks, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Remarks, new { @class = "form-control" })
        </div>
    </div>

    <div>
        <input type="hidden" name="CourseID" id="CourseID" value="0" />        
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
}
@section Scripts 
   {
    @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">                         
            $(document).ready(function () {
                commonmodule.init();                
            });
       </script>
    }

ims.web/Views/Enquiry/ThankYou.cshtml
@{
    ViewBag.Title = "Thank You";
}

<h3>You have submitted course enquiry. We will contact you for a details disucssion within 2 working days. Thank you...</h3>

<br/><br /><br /><br /><br /><br /><br /><br /><br /><br />